// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gmail-clone-backend/ent/email"
	"gmail-clone-backend/ent/schema"
	"gmail-clone-backend/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	emailFields := schema.Email{}.Fields()
	_ = emailFields
	// emailDescArchived is the schema descriptor for archived field.
	emailDescArchived := emailFields[4].Descriptor()
	// email.DefaultArchived holds the default value on creation for the archived field.
	email.DefaultArchived = emailDescArchived.Default.(bool)
	// emailDescRead is the schema descriptor for read field.
	emailDescRead := emailFields[5].Descriptor()
	// email.DefaultRead holds the default value on creation for the read field.
	email.DefaultRead = emailDescRead.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
